BOT_TOKEN=6591418180:AAGtCzP-Y1pRagY8o3rJutg3KtFEk82JY3c
BOT_NAME=Appmaker_firstBot
CHANNEL=appmakerfirstbot
URL_1=https://www.google.com/
URL_2=https://github.com/dashboard
INLINE_NUMBER=2
MARKUP_ROW_NUMBER=3
MARKUP_BUTTON_NUMBER=2