BOT_TOKEN=6591418180:AAGtCzP-Y1pRagY8o3rJutg3KtFEk82JY3c
BOT_NAME=Appmaker_firstBot
CHANNEL=appmakerfirstbot
URL_1=https://www.google.com/
URL_2=https://github.com/dashboard
KEYBOARD_BUTTON=[2, 3 , 5]
INLINE_KEYBOARD_BUTTON=[2 , 2 , 1]